spring:
  datasource:
    url: jdbc:mysql://101.132.151.81:13306/student
    username: root
    password: 123456

  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
  cache:
    cache-names: user
    type: ehcache


test:
  name: li


#    ehcache:
#      config: classpath:ehcache.xml